/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActiveDeploymentTelemetryRequest {
    /// List of Deployment request ID to get telemetry.
    #[serde(rename = "deployments")]
    pub deployments: Vec<String>,
    #[serde(rename = "ips")]
    pub ips: Vec<String>,
    /// Webhook URL that we should call to send the telemetry response back.
    #[serde(rename = "webhook_url", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<String>,
}

impl ActiveDeploymentTelemetryRequest {
    pub fn new(deployments: Vec<String>, ips: Vec<String>) -> ActiveDeploymentTelemetryRequest {
        ActiveDeploymentTelemetryRequest {
            deployments,
            ips,
            webhook_url: None,
        }
    }
}


