/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActiveDeploymentTelemetryResponse {
    /// Unique retrieval key to get the telemetry response.
    #[serde(rename = "retrieval_key")]
    pub retrieval_key: String,
    /// Expiration date of the retrieval key.
    #[serde(rename = "expire")]
    pub expire: String,
}

impl ActiveDeploymentTelemetryResponse {
    pub fn new(retrieval_key: String, expire: String) -> ActiveDeploymentTelemetryResponse {
        ActiveDeploymentTelemetryResponse {
            retrieval_key,
            expire,
        }
    }
}


