/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiModelLocationbeacon {
    /// The URL of the pingable location.
    #[serde(rename = "host")]
    pub host: String,
    /// The open UDP port number for UDP pings, if available.
    #[serde(rename = "udp_port", skip_serializing_if = "Option::is_none")]
    pub udp_port: Option<i32>,
    /// The open TCP port number for TCP pings, if available.
    #[serde(rename = "tcp_port", skip_serializing_if = "Option::is_none")]
    pub tcp_port: Option<i32>,
    #[serde(rename = "location")]
    pub location: Box<crate::models::ApiModelLocation>,
}

impl ApiModelLocationbeacon {
    pub fn new(host: String, location: crate::models::ApiModelLocation) -> ApiModelLocationbeacon {
        ApiModelLocationbeacon {
            host,
            udp_port: None,
            tcp_port: None,
            location: Box::new(location),
        }
    }
}


