/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiModelContainercrashdata {
    /// Auto Generated Field for exit_code
    #[serde(rename = "exit_code", skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,
    /// Auto Generated Field for message
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// Auto Generated Field for restart_count
    #[serde(rename = "restart_count", skip_serializing_if = "Option::is_none")]
    pub restart_count: Option<i32>,
}

impl ApiModelContainercrashdata {
    pub fn new() -> ApiModelContainercrashdata {
        ApiModelContainercrashdata {
            exit_code: None,
            message: None,
            restart_count: None,
        }
    }
}


