/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiModelContainerlogs {
    /// Auto Generated Field for logs
    #[serde(rename = "logs", skip_serializing_if = "Option::is_none")]
    pub logs: Option<String>,
    /// Auto Generated Field for encoding
    #[serde(rename = "encoding", skip_serializing_if = "Option::is_none")]
    pub encoding: Option<String>,
    /// Auto Generated Field for crash_logs
    #[serde(rename = "crash_logs", skip_serializing_if = "Option::is_none")]
    pub crash_logs: Option<String>,
    #[serde(rename = "crash_data", skip_serializing_if = "Option::is_none")]
    pub crash_data: Option<Box<crate::models::ApiModelContainercrashdata>>,
    /// Auto Generated Field for logs_link
    #[serde(rename = "logs_link", skip_serializing_if = "Option::is_none")]
    pub logs_link: Option<String>,
}

impl ApiModelContainerlogs {
    pub fn new() -> ApiModelContainerlogs {
        ApiModelContainerlogs {
            logs: None,
            encoding: None,
            crash_logs: None,
            crash_data: None,
            logs_link: None,
        }
    }
}


