/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppVersionWhitelistEntryPayload {
    /// CIDR to allow
    #[serde(rename = "cidr")]
    pub cidr: String,
    /// Label to organized your entries
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// If the Rule will be applied on runtime
    #[serde(rename = "is_active", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
}

impl AppVersionWhitelistEntryPayload {
    pub fn new(cidr: String) -> AppVersionWhitelistEntryPayload {
        AppVersionWhitelistEntryPayload {
            cidr,
            label: None,
            is_active: None,
        }
    }
}


