/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppVersionProbe {
    /// Your optimal value for Latency
    #[serde(rename = "optimal_ping")]
    pub optimal_ping: i32,
    /// Your reject value for Latency
    #[serde(rename = "rejected_ping")]
    pub rejected_ping: i32,
}

impl AppVersionProbe {
    pub fn new(optimal_ping: i32, rejected_ping: i32) -> AppVersionProbe {
        AppVersionProbe {
            optimal_ping,
            rejected_ping,
        }
    }
}


