/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppVersionEnv {
    /// The Key where the Environment Variable will be set
    #[serde(rename = "key")]
    pub key: String,
    /// The Value to retrieve at the Key
    #[serde(rename = "value")]
    pub value: String,
    /// This will encrypt the value in our database, won't be readable by external source
    #[serde(rename = "is_secret", skip_serializing_if = "Option::is_none")]
    pub is_secret: Option<bool>,
}

impl AppVersionEnv {
    pub fn new(key: String, value: String) -> AppVersionEnv {
        AppVersionEnv {
            key,
            value,
            is_secret: None,
        }
    }
}


