/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppVersionCreateResponse {
    /// If the creation happened correctly
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<Box<crate::models::AppVersionPayload>>,
}

impl AppVersionCreateResponse {
    pub fn new() -> AppVersionCreateResponse {
        AppVersionCreateResponse {
            success: None,
            version: None,
        }
    }
}


