/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppVersionWhitelistResponse {
    #[serde(rename = "whitelist_entries", skip_serializing_if = "Option::is_none")]
    pub whitelist_entries: Option<Vec<crate::models::AppVersionWhitelistEntry>>,
}

impl AppVersionWhitelistResponse {
    pub fn new() -> AppVersionWhitelistResponse {
        AppVersionWhitelistResponse {
            whitelist_entries: None,
        }
    }
}


