/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationPatch {
    /// Application name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// If the application can be deployed
    #[serde(rename = "is_active", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    /// If the telemetry agent is installed on the versions of this app.
    #[serde(rename = "is_telemetry_agent_active", skip_serializing_if = "Option::is_none")]
    pub is_telemetry_agent_active: Option<bool>,
    /// Image base64 string
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

impl ApplicationPatch {
    pub fn new() -> ApplicationPatch {
        ApplicationPatch {
            name: None,
            is_active: None,
            is_telemetry_agent_active: None,
            image: None,
        }
    }
}


