/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkSessionPost {
    /// List of Creation Reply
    #[serde(rename = "sessions")]
    pub sessions: Vec<crate::models::SessionRequest>,
    /// List of Creation Errors Reply
    #[serde(rename = "errors")]
    pub errors: Vec<String>,
}

impl BulkSessionPost {
    pub fn new(sessions: Vec<crate::models::SessionRequest>, errors: Vec<String>) -> BulkSessionPost {
        BulkSessionPost {
            sessions,
            errors,
        }
    }
}


