/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComponentCredentials {
    /// Username for the component's private repository.
    #[serde(rename = "username")]
    pub username: String,
    /// Password (token) of the component's private repository.
    #[serde(rename = "token")]
    pub token: String,
}

impl ComponentCredentials {
    pub fn new(username: String, token: String) -> ComponentCredentials {
        ComponentCredentials {
            username,
            token,
        }
    }
}


