/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomBulkSessionsModel {
    #[serde(rename = "sessions", skip_serializing_if = "Option::is_none")]
    pub sessions: Option<Vec<crate::models::CustomBulkSessionModel>>,
}

impl CustomBulkSessionsModel {
    pub fn new() -> CustomBulkSessionsModel {
        CustomBulkSessionsModel {
            sessions: None,
        }
    }
}


