/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomSessionDeleteModel {
    /// List of Custom IDs to Delete
    #[serde(rename = "sessions")]
    pub sessions: Vec<String>,
}

impl CustomSessionDeleteModel {
    pub fn new(sessions: Vec<String>) -> CustomSessionDeleteModel {
        CustomSessionDeleteModel {
            sessions,
        }
    }
}


