/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteRequestReceived {
    /// Message to confirm that the delete request has been received
    #[serde(rename = "message")]
    pub message: String,
}

impl DeleteRequestReceived {
    pub fn new(message: String) -> DeleteRequestReceived {
        DeleteRequestReceived {
            message,
        }
    }
}


