/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Delete {
    /// A message depending of the request termination
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "deployment_summary", skip_serializing_if = "Option::is_none")]
    pub deployment_summary: Option<Box<crate::models::Status>>,
}

impl Delete {
    pub fn new(message: String) -> Delete {
        Delete {
            message,
            deployment_summary: None,
        }
    }
}


