/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentSessionContext {
    /// Unique UUID
    #[serde(rename = "session_id")]
    pub session_id: String,
    /// Current status of the session
    #[serde(rename = "status")]
    pub status: String,
    /// If the session is linked to a Ready deployment
    #[serde(rename = "ready")]
    pub ready: bool,
    /// If the session is linked to a deployment
    #[serde(rename = "linked")]
    pub linked: bool,
    /// Type of session created
    #[serde(rename = "kind")]
    pub kind: String,
    /// Count of user this session currently have
    #[serde(rename = "user_count")]
    pub user_count: i32,
}

impl DeploymentSessionContext {
    pub fn new(session_id: String, status: String, ready: bool, linked: bool, kind: String, user_count: i32) -> DeploymentSessionContext {
        DeploymentSessionContext {
            session_id,
            status,
            ready,
            linked,
            kind,
            user_count,
        }
    }
}


