/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Deployment {
    /// Unique UUID
    #[serde(rename = "request_id")]
    pub request_id: String,
    /// The public IP
    #[serde(rename = "public_ip")]
    pub public_ip: String,
    /// Current status of Deployment
    #[serde(rename = "status")]
    pub status: String,
    /// if the deployment is ready
    #[serde(rename = "ready")]
    pub ready: bool,
    /// if the deployment ACL is active
    #[serde(rename = "whitelisting_active", skip_serializing_if = "Option::is_none")]
    pub whitelisting_active: Option<bool>,
    /// 
    #[serde(rename = "fqdn")]
    pub fqdn: String,
    #[serde(rename = "ports", skip_serializing_if = "Option::is_none")]
    pub ports: Option<::std::collections::HashMap<String, crate::models::PortMapping>>,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<Box<crate::models::DeploymentLocation>>,
    /// List of tags associated with the deployment
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// The Capacity of the Deployment
    #[serde(rename = "sockets", skip_serializing_if = "Option::is_none")]
    pub sockets: Option<i32>,
    /// The Capacity Usage of the Deployment
    #[serde(rename = "sockets_usage", skip_serializing_if = "Option::is_none")]
    pub sockets_usage: Option<i32>,
    /// If the deployment is joinable by sessions
    #[serde(rename = "is_joinable_by_session", skip_serializing_if = "Option::is_none")]
    pub is_joinable_by_session: Option<bool>,
}

impl Deployment {
    pub fn new(request_id: String, public_ip: String, status: String, ready: bool, whitelisting_active: bool, fqdn: String) -> Deployment {
        Deployment {
            request_id,
            public_ip,
            status,
            ready,
            whitelisting_active: Some(whitelisting_active),
            fqdn,
            ports: None,
            location: None,
            tags: None,
            sockets: None,
            sockets_usage: None,
            is_joinable_by_session: None,
        }
    }
}


