/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentLocation {
    /// City of the deployment
    #[serde(rename = "city")]
    pub city: String,
    /// Country of the deployment
    #[serde(rename = "country")]
    pub country: String,
    /// Continent of the deployment
    #[serde(rename = "continent")]
    pub continent: String,
    /// Administrative division of the deployment
    #[serde(rename = "administrative_division")]
    pub administrative_division: String,
    /// Timezone of the deployment
    #[serde(rename = "timezone")]
    pub timezone: String,
    /// Latitude of the deployment
    #[serde(rename = "latitude")]
    pub latitude: f32,
    /// Longitude of the deployment
    #[serde(rename = "longitude")]
    pub longitude: f32,
}

impl DeploymentLocation {
    pub fn new(city: String, country: String, continent: String, administrative_division: String, timezone: String, latitude: f32, longitude: f32) -> DeploymentLocation {
        DeploymentLocation {
            city,
            country,
            continent,
            administrative_division,
            timezone,
            latitude,
            longitude,
        }
    }
}


