/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentUpdateResponse {
    /// If the deployment is joinable by sessions
    #[serde(rename = "is_joinable_by_session")]
    pub is_joinable_by_session: bool,
}

impl DeploymentUpdateResponse {
    pub fn new(is_joinable_by_session: bool) -> DeploymentUpdateResponse {
        DeploymentUpdateResponse {
            is_joinable_by_session,
        }
    }
}


