/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeployEnvModel {
    /// The Key to retrieve the value in your instance
    #[serde(rename = "key")]
    pub key: String,
    /// The value to set in your instance
    #[serde(rename = "value")]
    pub value: String,
    /// If set to true, the value will be encrypted during the process of deployment
    #[serde(rename = "is_hidden", skip_serializing_if = "Option::is_none")]
    pub is_hidden: Option<bool>,
}

impl DeployEnvModel {
    pub fn new(key: String, value: String) -> DeployEnvModel {
        DeployEnvModel {
            key,
            value,
            is_hidden: None,
        }
    }
}


