/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentTagResponse {
    /// The name of the tag
    #[serde(rename = "name")]
    pub name: String,
    /// UTC time of policy creation
    #[serde(rename = "create_time", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<String>,
    /// UTC time of policy last update
    #[serde(rename = "last_updated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
}

impl DeploymentTagResponse {
    pub fn new(name: String) -> DeploymentTagResponse {
        DeploymentTagResponse {
            name,
            create_time: None,
            last_updated: None,
        }
    }
}


