/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentListData {
    /// Unique UUID
    #[serde(rename = "request_id")]
    pub request_id: String,
    /// The FQDN that allow to connect to your deployment
    #[serde(rename = "fqdn")]
    pub fqdn: String,
    /// Timestamp of the deployment when it is up and running
    #[serde(rename = "start_time")]
    pub start_time: String,
    /// If the deployment is ready
    #[serde(rename = "ready")]
    pub ready: bool,
    /// The public IP
    #[serde(rename = "public_ip")]
    pub public_ip: String,
    #[serde(rename = "ports", skip_serializing_if = "Option::is_none")]
    pub ports: Option<::std::collections::HashMap<String, crate::models::PortMapping>>,
    /// List of tags associated with the deployment
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// The capacity of the deployment
    #[serde(rename = "sockets", skip_serializing_if = "Option::is_none")]
    pub sockets: Option<i32>,
    /// The capacity usage of the deployment
    #[serde(rename = "sockets_usage", skip_serializing_if = "Option::is_none")]
    pub sockets_usage: Option<i32>,
    /// If the deployment is joinable by sessions
    #[serde(rename = "is_joinable_by_session", skip_serializing_if = "Option::is_none")]
    pub is_joinable_by_session: Option<bool>,
}

impl DeploymentListData {
    pub fn new(request_id: String, fqdn: String, start_time: String, ready: bool, public_ip: String) -> DeploymentListData {
        DeploymentListData {
            request_id,
            fqdn,
            start_time,
            ready,
            public_ip,
            ports: None,
            tags: None,
            sockets: None,
            sockets_usage: None,
            is_joinable_by_session: None,
        }
    }
}


