/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Deployments {
    /// List of active deployments
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<crate::models::DeploymentListData>>,
    /// Total Objects in the Database
    #[serde(rename = "total_count", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i32>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::Pagination>>,
    /// Extra Messages for the query
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<Vec<String>>,
}

impl Deployments {
    pub fn new() -> Deployments {
        Deployments {
            data: None,
            total_count: None,
            pagination: None,
            message: None,
        }
    }
}


