/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentUpdatePayload {
    /// Whether a session can connect to this deployment or not.
    #[serde(rename = "is_joinable_by_session", skip_serializing_if = "Option::is_none")]
    pub is_joinable_by_session: Option<bool>,
}

impl DeploymentUpdatePayload {
    pub fn new() -> DeploymentUpdatePayload {
        DeploymentUpdatePayload {
            is_joinable_by_session: None,
        }
    }
}


