/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EndpointStoragePatchPayload {
    /// Name of the Endpoint Storage
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Your access key ID to connect to your S3 Bucket.
    #[serde(rename = "access_key_id", skip_serializing_if = "Option::is_none")]
    pub access_key_id: Option<String>,
    /// Full URL to your S3 Bucket with https or http. It's recommended to not include your bucket name as a subdomain
    #[serde(rename = "endpoint", skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
    /// Your secret access key to connect to your S3 Bucket. Will be encrypted.
    #[serde(rename = "bucket", skip_serializing_if = "Option::is_none")]
    pub bucket: Option<String>,
    /// Your secret access key to connect to your S3 Bucket. Will be encrypted.
    #[serde(rename = "secret_access_key", skip_serializing_if = "Option::is_none")]
    pub secret_access_key: Option<String>,
}

impl EndpointStoragePatchPayload {
    pub fn new() -> EndpointStoragePatchPayload {
        EndpointStoragePatchPayload {
            name: None,
            access_key_id: None,
            endpoint: None,
            bucket: None,
            secret_access_key: None,
        }
    }
}


