/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FleetPoliciesPatchPayload {
    /// Name of the Policy
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// If the Policy is enabled. Defaults to true.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Type of the Policy. See our documentation for more information on the type and it's data.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<Type>,
    /// Minimum deployments at all time
    #[serde(rename = "minimum", skip_serializing_if = "Option::is_none")]
    pub minimum: Option<i32>,
    /// Maximum deployments for the provided type.
    #[serde(rename = "maximum", skip_serializing_if = "Option::is_none")]
    pub maximum: Option<i32>,
    /// Based on the number of sockets connected, how filled should a session deployment be before initiating a scale-up deployment. Float between 0.1 and 1.
    #[serde(rename = "threshold", skip_serializing_if = "Option::is_none")]
    pub threshold: Option<f32>,
    /// JSON object for your filters. See our documentation for more information.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    /// UTC time of policy creation
    #[serde(rename = "create_time", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<String>,
    /// UTC time of policy last update
    #[serde(rename = "last_updated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
}

impl FleetPoliciesPatchPayload {
    pub fn new() -> FleetPoliciesPatchPayload {
        FleetPoliciesPatchPayload {
            name: None,
            enabled: None,
            _type: None,
            minimum: None,
            maximum: None,
            threshold: None,
            data: None,
            create_time: None,
            last_updated: None,
        }
    }
}

/// Type of the Policy. See our documentation for more information on the type and it's data.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Location")]
    Location,
    #[serde(rename = "Tag")]
    Tag,
    #[serde(rename = "Coordinates")]
    Coordinates,
}

