/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FleetList {
    /// List of Fleets
    #[serde(rename = "fleets", skip_serializing_if = "Option::is_none")]
    pub fleets: Option<Vec<crate::models::FleetGetResponse>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::Pagination>>,
}

impl FleetList {
    pub fn new() -> FleetList {
        FleetList {
            fleets: None,
            pagination: None,
        }
    }
}


