/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FleetPostPayload {
    /// Name of the Fleet
    #[serde(rename = "name")]
    pub name: String,
    /// If the Fleet is enabled. Defaults to false.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl FleetPostPayload {
    pub fn new(name: String) -> FleetPostPayload {
        FleetPostPayload {
            name,
            enabled: None,
        }
    }
}


