/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FleetGetResponse {
    /// Name of the Fleet
    #[serde(rename = "name")]
    pub name: String,
    /// If the Fleet is enabled. Defaults to false.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// UTC time of fleet creation
    #[serde(rename = "create_time", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<String>,
    /// UTC time of fleet last update
    #[serde(rename = "last_updated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
}

impl FleetGetResponse {
    pub fn new(name: String) -> FleetGetResponse {
        FleetGetResponse {
            name,
            enabled: None,
            create_time: None,
            last_updated: None,
        }
    }
}


