/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeoIpListModel {
    /// IP
    #[serde(rename = "ip")]
    pub ip: String,
    /// Latitude
    #[serde(rename = "latitude")]
    pub latitude: f32,
    /// Longitude
    #[serde(rename = "longitude")]
    pub longitude: f32,
}

impl GeoIpListModel {
    pub fn new(ip: String, latitude: f32, longitude: f32) -> GeoIpListModel {
        GeoIpListModel {
            ip,
            latitude,
            longitude,
        }
    }
}


