/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IpAddressesLookupResponse {
    /// IP Addresses
    #[serde(rename = "addresses")]
    pub addresses: Vec<crate::models::IpAddressLookupResponse>,
}

impl IpAddressesLookupResponse {
    pub fn new(addresses: Vec<crate::models::IpAddressLookupResponse>) -> IpAddressesLookupResponse {
        IpAddressesLookupResponse {
            addresses,
        }
    }
}


