/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IpAddressLookupResponse {
    /// IP address type
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    /// IP address
    #[serde(rename = "ip_address")]
    pub ip_address: String,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<Box<crate::models::IpAddressLookupLocation>>,
}

impl IpAddressLookupResponse {
    pub fn new(ip_address: String) -> IpAddressLookupResponse {
        IpAddressLookupResponse {
            _type: None,
            ip_address,
            location: None,
        }
    }
}


