/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LobbyReadResponse {
    /// Name of the lobby
    #[serde(rename = "name")]
    pub name: String,
    /// URL of the lobby
    #[serde(rename = "url")]
    pub url: String,
    /// Status of the lobby
    #[serde(rename = "status")]
    pub status: String,
}

impl LobbyReadResponse {
    pub fn new(name: String, url: String, status: String) -> LobbyReadResponse {
        LobbyReadResponse {
            name,
            url,
            status,
        }
    }
}


