/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocationBeaconList {
    /// Total number of active location beacons
    #[serde(rename = "locations", skip_serializing_if = "Option::is_none")]
    pub locations: Option<Vec<crate::models::ApiModelLocationbeacon>>,
    /// List of active location beacons
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
}

impl LocationBeaconList {
    pub fn new() -> LocationBeaconList {
        LocationBeaconList {
            locations: None,
            count: None,
        }
    }
}


