/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchmakerReleaseResponseAllOf {
    /// Name of the matchmaker component to use as the Open Match frontend.
    #[serde(rename = "frontend_component_name")]
    pub frontend_component_name: String,
    /// Name of the matchmaker component to use as the Open Match director.
    #[serde(rename = "director_component_name")]
    pub director_component_name: String,
    /// Name of the matchmaker component to use as the Open Match match function.
    #[serde(rename = "match_function_component_name")]
    pub match_function_component_name: String,
}

impl MatchmakerReleaseResponseAllOf {
    pub fn new(frontend_component_name: String, director_component_name: String, match_function_component_name: String) -> MatchmakerReleaseResponseAllOf {
        MatchmakerReleaseResponseAllOf {
            frontend_component_name,
            director_component_name,
            match_function_component_name,
        }
    }
}


