/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchmakerManagedReleaseCreate {
    /// Name of the matchmaker release. Should be unique, and will be used to differentiate your releases.
    #[serde(rename = "version")]
    pub version: String,
    /// Name of the matchmaker release configuration to use for this managed release.
    #[serde(rename = "release_config_name")]
    pub release_config_name: String,
}

impl MatchmakerManagedReleaseCreate {
    pub fn new(version: String, release_config_name: String) -> MatchmakerManagedReleaseCreate {
        MatchmakerManagedReleaseCreate {
            version,
            release_config_name,
        }
    }
}


