/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchmakerComponentEnvsUpdate {
    /// Name of the ENV variable.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Value of the ENV variable.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl MatchmakerComponentEnvsUpdate {
    pub fn new() -> MatchmakerComponentEnvsUpdate {
        MatchmakerComponentEnvsUpdate {
            key: None,
            value: None,
        }
    }
}


