/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchmakerReleaseConfigResponse {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    /// Matchmaker configuration name. Must be unique.
    #[serde(rename = "name")]
    pub name: String,
    /// Matchmaker configuration, parsed as a string.
    #[serde(rename = "configuration")]
    pub configuration: String,
}

impl MatchmakerReleaseConfigResponse {
    pub fn new(created_at: String, updated_at: String, name: String, configuration: String) -> MatchmakerReleaseConfigResponse {
        MatchmakerReleaseConfigResponse {
            created_at,
            updated_at,
            name,
            configuration,
        }
    }
}


