/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchmakerComponentEnvsResponse {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    /// Name of the ENV variable.
    #[serde(rename = "key")]
    pub key: String,
    /// Value of the ENV variable.
    #[serde(rename = "value")]
    pub value: String,
}

impl MatchmakerComponentEnvsResponse {
    pub fn new(created_at: String, updated_at: String, key: String, value: String) -> MatchmakerComponentEnvsResponse {
        MatchmakerComponentEnvsResponse {
            created_at,
            updated_at,
            key,
            value,
        }
    }
}


