/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchmakerManagedReleaseUpdateAllOf {
    /// Name of the matchmaker release configuration to use for this managed release.
    #[serde(rename = "release_config_name", skip_serializing_if = "Option::is_none")]
    pub release_config_name: Option<String>,
}

impl MatchmakerManagedReleaseUpdateAllOf {
    pub fn new() -> MatchmakerManagedReleaseUpdateAllOf {
        MatchmakerManagedReleaseUpdateAllOf {
            release_config_name: None,
        }
    }
}


