/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchmakerReleaseConfigResponseAllOf {
    /// Matchmaker configuration name. Must be unique.
    #[serde(rename = "name")]
    pub name: String,
    /// Matchmaker configuration, parsed as a string.
    #[serde(rename = "configuration")]
    pub configuration: String,
}

impl MatchmakerReleaseConfigResponseAllOf {
    pub fn new(name: String, configuration: String) -> MatchmakerReleaseConfigResponseAllOf {
        MatchmakerReleaseConfigResponseAllOf {
            name,
            configuration,
        }
    }
}


