/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchmakerComponentCreate {
    /// Matchmaker component name. Must be unique.
    #[serde(rename = "name")]
    pub name: String,
    /// Container repository where the component's image is hosted.
    #[serde(rename = "repository")]
    pub repository: String,
    /// Container image to use for this component.
    #[serde(rename = "image")]
    pub image: String,
    /// Tag of the container image to use for this component.
    #[serde(rename = "tag")]
    pub tag: String,
    /// Private repo credentials to use for pulling the image, if applicable.
    #[serde(rename = "credentials", skip_serializing_if = "Option::is_none")]
    pub credentials: Option<Box<crate::models::ComponentCredentials>>,
}

impl MatchmakerComponentCreate {
    pub fn new(name: String, repository: String, image: String, tag: String) -> MatchmakerComponentCreate {
        MatchmakerComponentCreate {
            name,
            repository,
            image,
            tag,
            credentials: None,
        }
    }
}


