/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchmakerComponentEnvsResponseAllOf {
    /// Name of the ENV variable.
    #[serde(rename = "key")]
    pub key: String,
    /// Value of the ENV variable.
    #[serde(rename = "value")]
    pub value: String,
}

impl MatchmakerComponentEnvsResponseAllOf {
    pub fn new(key: String, value: String) -> MatchmakerComponentEnvsResponseAllOf {
        MatchmakerComponentEnvsResponseAllOf {
            key,
            value,
        }
    }
}


