/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchmakerReleaseUpdateAllOf {
    /// Name of the matchmaker component to use as the Open Match frontend.
    #[serde(rename = "frontend_component_name", skip_serializing_if = "Option::is_none")]
    pub frontend_component_name: Option<String>,
    /// Name of the matchmaker component to use as the Open Match director.
    #[serde(rename = "director_component_name", skip_serializing_if = "Option::is_none")]
    pub director_component_name: Option<String>,
    /// Name of the matchmaker component to use as the Open Match match function.
    #[serde(rename = "match_function_component_name", skip_serializing_if = "Option::is_none")]
    pub match_function_component_name: Option<String>,
}

impl MatchmakerReleaseUpdateAllOf {
    pub fn new() -> MatchmakerReleaseUpdateAllOf {
        MatchmakerReleaseUpdateAllOf {
            frontend_component_name: None,
            director_component_name: None,
            match_function_component_name: None,
        }
    }
}


