/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchmakerCreate {
    /// Name of the Matchmaker.
    #[serde(rename = "name")]
    pub name: String,
}

impl MatchmakerCreate {
    pub fn new(name: String) -> MatchmakerCreate {
        MatchmakerCreate {
            name,
        }
    }
}


