/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchmakerComponentEnvListResponse {
    /// Number of matchmaker component envs for the component.
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "data")]
    pub data: Box<crate::models::MatchmakerComponentEnvsResponse>,
}

impl MatchmakerComponentEnvListResponse {
    pub fn new(count: i32, data: crate::models::MatchmakerComponentEnvsResponse) -> MatchmakerComponentEnvListResponse {
        MatchmakerComponentEnvListResponse {
            count,
            data: Box::new(data),
        }
    }
}


