/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NetworkMetricsModel {
    #[serde(rename = "receive", skip_serializing_if = "Option::is_none")]
    pub receive: Option<Box<crate::models::MetricsModel>>,
    #[serde(rename = "transmit", skip_serializing_if = "Option::is_none")]
    pub transmit: Option<Box<crate::models::MetricsModel>>,
}

impl NetworkMetricsModel {
    pub fn new() -> NetworkMetricsModel {
        NetworkMetricsModel {
            receive: None,
            transmit: None,
        }
    }
}


