/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PullProfilePatchPayload {
    /// Name of the pull profile
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Source in the S3 bucket to fetch from
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// If the source is a File or a Directory
    #[serde(rename = "source_type", skip_serializing_if = "Option::is_none")]
    pub source_type: Option<SourceType>,
    /// Destination path where your source will be uploaded in your container. Make sure to avoid protected destinations, such as `/etc/`, as this will prevent the files from being copied to your deployment, and will make your deployment fail. Make sure a normal user can write to the destination folder.
    #[serde(rename = "destination", skip_serializing_if = "Option::is_none")]
    pub destination: Option<String>,
}

impl PullProfilePatchPayload {
    pub fn new() -> PullProfilePatchPayload {
        PullProfilePatchPayload {
            name: None,
            source: None,
            source_type: None,
            destination: None,
        }
    }
}

/// If the source is a File or a Directory
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SourceType {
    #[serde(rename = "File")]
    File,
    #[serde(rename = "Folder")]
    Folder,
}

