/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PullProfilesListResponse {
    #[serde(rename = "pull_profiles", skip_serializing_if = "Option::is_none")]
    pub pull_profiles: Option<Vec<crate::models::PullProfileGetResponse>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::Pagination>>,
}

impl PullProfilesListResponse {
    pub fn new() -> PullProfilesListResponse {
        PullProfilesListResponse {
            pull_profiles: None,
            pagination: None,
        }
    }
}


