/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RelayUserRevokePayload {
    /// Session Request ID (ex: 0724828881e2-S)
    #[serde(rename = "session_id")]
    pub session_id: String,
    /// Relay Authorization Token
    #[serde(rename = "authorization_token")]
    pub authorization_token: i32,
}

impl RelayUserRevokePayload {
    pub fn new(session_id: String, authorization_token: i32) -> RelayUserRevokePayload {
        RelayUserRevokePayload {
            session_id,
            authorization_token,
        }
    }
}


