/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RelaySessionUserResponse {
    /// The IP Address of the user
    #[serde(rename = "ip_address", skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    /// The latitude of the user
    #[serde(rename = "latitude", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f32>,
    /// The longitude of the user
    #[serde(rename = "longitude", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f32>,
    /// The authorization token of the user
    #[serde(rename = "authorization_token", skip_serializing_if = "Option::is_none")]
    pub authorization_token: Option<i32>,
}

impl RelaySessionUserResponse {
    pub fn new() -> RelaySessionUserResponse {
        RelaySessionUserResponse {
            ip_address: None,
            latitude: None,
            longitude: None,
            authorization_token: None,
        }
    }
}


