/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RelayUserAuthorizePayload {
    /// Session Request ID (ex: 0724828881e2-S)
    #[serde(rename = "session_id")]
    pub session_id: String,
    /// User Ip to Authorize
    #[serde(rename = "user_ip")]
    pub user_ip: String,
}

impl RelayUserAuthorizePayload {
    pub fn new(session_id: String, user_ip: String) -> RelayUserAuthorizePayload {
        RelayUserAuthorizePayload {
            session_id,
            user_ip,
        }
    }
}


