/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RelaySessionCreatePayload {
    /// List of IP Addresses of session users
    #[serde(rename = "users")]
    pub users: Vec<crate::models::RelaySessionUser>,
    /// List of location filters to apply to the session
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Vec<crate::models::RelayFilterModel>>,
    /// URL to send the session data to
    #[serde(rename = "webhook_url", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<String>,
}

impl RelaySessionCreatePayload {
    pub fn new(users: Vec<crate::models::RelaySessionUser>) -> RelaySessionCreatePayload {
        RelaySessionCreatePayload {
            users,
            filters: None,
            webhook_url: None,
        }
    }
}


