/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RelaySessionUser {
    /// IP Address of session user
    #[serde(rename = "ip")]
    pub ip: String,
}

impl RelaySessionUser {
    pub fn new(ip: String) -> RelaySessionUser {
        RelaySessionUser {
            ip,
        }
    }
}


