/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelectorModel {
    /// The Tag to filter potential Deployment with this Selector
    #[serde(rename = "tag")]
    pub tag: String,
    /// If True, will not try to filter Deployment and only tag the Session
    #[serde(rename = "tag_only", skip_serializing_if = "Option::is_none")]
    pub tag_only: Option<bool>,
    /// Environment Variable to inject in new Deployment created by App Version with auto-deploy
    #[serde(rename = "env", skip_serializing_if = "Option::is_none")]
    pub env: Option<Box<crate::models::SelectorEnvModel>>,
}

impl SelectorModel {
    pub fn new(tag: String) -> SelectorModel {
        SelectorModel {
            tag,
            tag_only: None,
            env: None,
        }
    }
}


