/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionStopResponse {
    /// The id of the request for a deployment
    #[serde(rename = "session_id")]
    pub session_id: String,
}

impl SessionStopResponse {
    pub fn new(session_id: String) -> SessionStopResponse {
        SessionStopResponse {
            session_id,
        }
    }
}


