/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionBulkStopPayload {
    /// Filters used to match with sessions
    #[serde(rename = "filters")]
    pub filters: Vec<crate::models::SessionBulkStopFiltersPayload>,
}

impl SessionBulkStopPayload {
    pub fn new(filters: Vec<crate::models::SessionBulkStopFiltersPayload>) -> SessionBulkStopPayload {
        SessionBulkStopPayload {
            filters,
        }
    }
}


