/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionBulkStopResponse {
    /// A list sessions that can be processed to be stopped
    #[serde(rename = "processable")]
    pub processable: Vec<crate::models::SessionStopResponse>,
}

impl SessionBulkStopResponse {
    pub fn new(processable: Vec<crate::models::SessionStopResponse>) -> SessionBulkStopResponse {
        SessionBulkStopResponse {
            processable,
        }
    }
}


