/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionUserContext {
    /// Users in the session
    #[serde(rename = "session_users")]
    pub session_users: Vec<crate::models::SessionUser>,
}

impl SessionUserContext {
    pub fn new(session_users: Vec<crate::models::SessionUser>) -> SessionUserContext {
        SessionUserContext {
            session_users,
        }
    }
}


