/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionDelete {
    /// A message depending of the request termination
    #[serde(rename = "message")]
    pub message: String,
    /// The Unique Identifier of the Session
    #[serde(rename = "session_id")]
    pub session_id: String,
    /// Custom ID if Available
    #[serde(rename = "custom_id", skip_serializing_if = "Option::is_none")]
    pub custom_id: Option<String>,
}

impl SessionDelete {
    pub fn new(message: String, session_id: String) -> SessionDelete {
        SessionDelete {
            message,
            session_id,
            custom_id: None,
        }
    }
}


