/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionBulkStopFiltersPayload {
    /// The field on which to apply the filter
    #[serde(rename = "field")]
    pub field: Field,
    /// Values that will be used for the filter
    #[serde(rename = "values")]
    pub values: Vec<String>,
    /// Types of filter used. Possible values are: ['any', 'all', 'not']
    #[serde(rename = "filter_type")]
    pub filter_type: FilterType,
}

impl SessionBulkStopFiltersPayload {
    pub fn new(field: Field, values: Vec<String>, filter_type: FilterType) -> SessionBulkStopFiltersPayload {
        SessionBulkStopFiltersPayload {
            field,
            values,
            filter_type,
        }
    }
}

/// The field on which to apply the filter
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Field {
    #[serde(rename = "session_id")]
    SessionId,
    #[serde(rename = "deployment_tags")]
    DeploymentTags,
    #[serde(rename = "request_id")]
    RequestId,
}
/// Types of filter used. Possible values are: ['any', 'all', 'not']
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FilterType {
    #[serde(rename = "any")]
    Any,
    #[serde(rename = "all")]
    All,
    #[serde(rename = "not")]
    Not,
}

