/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionFilterModel {
    /// The field to filter
    #[serde(rename = "field")]
    pub field: String,
    /// The values to filter
    #[serde(rename = "values")]
    pub values: Vec<String>,
    /// The type of filter
    #[serde(rename = "filter_type")]
    pub filter_type: FilterType,
}

impl SessionFilterModel {
    pub fn new(field: String, values: Vec<String>, filter_type: FilterType) -> SessionFilterModel {
        SessionFilterModel {
            field,
            values,
            filter_type,
        }
    }
}

/// The type of filter
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FilterType {
    #[serde(rename = "any")]
    Any,
    #[serde(rename = "all")]
    All,
    #[serde(rename = "not")]
    Not,
}

