/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tag {
    /// Tag's Key
    #[serde(rename = "key")]
    pub key: String,
    /// Tag's Value
    #[serde(rename = "value")]
    pub value: String,
}

impl Tag {
    pub fn new(key: String, value: String) -> Tag {
        Tag {
            key,
            value,
        }
    }
}


