/*
 * Codema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@edgegap.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TotalMetricsModel {
    #[serde(rename = "receive_total", skip_serializing_if = "Option::is_none")]
    pub receive_total: Option<Box<crate::models::MetricsModel>>,
    #[serde(rename = "transmit_total", skip_serializing_if = "Option::is_none")]
    pub transmit_total: Option<Box<crate::models::MetricsModel>>,
    #[serde(rename = "disk_read_total", skip_serializing_if = "Option::is_none")]
    pub disk_read_total: Option<Box<crate::models::MetricsModel>>,
    #[serde(rename = "disk_write_total", skip_serializing_if = "Option::is_none")]
    pub disk_write_total: Option<Box<crate::models::MetricsModel>>,
}

impl TotalMetricsModel {
    pub fn new() -> TotalMetricsModel {
        TotalMetricsModel {
            receive_total: None,
            transmit_total: None,
            disk_read_total: None,
            disk_write_total: None,
        }
    }
}


